document.write ("<table cellpadding=0 cellspacing=0 border=0 width=900 background='http://www.cnr.cn/js_images/js_bg.gif'>                                                         ");
document.write ("<tr>                                                                                                                                        ");
document.write ("	<td width=900 valign='top' align='center'>                                                              ");
document.write ("		<table cellpadding=0 cellspacing=0 border=0 width='900'>                                                                                 ");
document.write ("		<tr>                                                                                                                                     ");
document.write ("		<td width='9'></td>                                                                                                                     ");
document.write ("		<td style='padding-top:5px' valign='top' align='left'><font color=#6F7072>|</font></td>                                                       ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/' target=_blank><font color=#6F7072>首页</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                       ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/pic/' target=_blank><font color=#6F7072>图片</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/caijing/' target=_blank><font color=#6F7072>财经</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/sports/' target=_blank><font color=#6F7072>体育</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/90/' target=_blank><font color=#6F7072>音乐</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/library/' target=_blank><font color=#6F7072>书院</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://auto.cnr.cn/' target=_blank><font color=#6F7072>汽车</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/lvyou/' target=_blank><font color=#6F7072>旅游</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><font color=#6F7072>房产</font></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/cate/' target=_blank><font color=#6F7072>美食</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/military/' target=_blank><font color=#6F7072>军事</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/minzu/' target=_blank><font color=#6F7072>民族</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.nihaotw.com/' target=_blank><font color=#6F7072>台湾</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://qh.cnr.cn/' target=_blank><font color=#6F7072>青海</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://gz.cnr.cn/' target=_blank><font color=#6F7072>贵州</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://nx.cnr.cn' target=_blank><font color=#6F7072>宁夏</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://xj.cnr.cn' target=_blank><font color=#6F7072>新疆</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://gs.cnr.cn' target=_blank><font color=#6F7072>甘肃</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://xm.cnr.cn' target=_blank><font color=#6F7072>厦门</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' style='font-size:12px;padding-top:6px' valign='top'><a href='http://hn.cnr.cn' target=_blank><font color=#6F7072>河南</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top' align='right'><font color=#6F7072>|</font></td>                                                         ");
document.write ("		<td width='9'></td>                                                                                                                     ");
document.write ("		</tr>                                                                                                                                    ");
document.write ("		<tr><td colspan='43' background='http://www.cnr.cn/js_images/js_pic_007.jpg' height='1'></td></tr>                                                            ");
document.write ("		</table>                                                                                                                                 ");
document.write ("		<table cellpadding=0 cellspacing=0 border=0 width='900'>                                                                                 ");
document.write ("		<tr>                                                                                                                                     ");
document.write ("		<td width='9'></td>                                                                                                                     ");
document.write ("		<td style='padding-top:5px' valign='top' align='left'><font color=#6F7072>|</font></td>                                                         ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://media.cnr.cn/index.jsp' target=_blank><font color=#6F7072>中广在线</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.radio.cn/' target=_blank><font color=#6F7072>银河台</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/yht/zz' target=_blank><font color=#6F7072>NJ电子杂志</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'>&nbsp;<a href='http://www.gardenv.com/' target=_blank><font color=#6F7072>视界乐园</font></a>&nbsp;</td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/luntan/' target=_blank><font color=#6F7072>中广评论</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://life.cnr.cn/' target=_blank><font color=#6F7072>中广社区</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://211.89.225.11/vip/vip22/ft_index.jsp' target=_blank><font color=#6F7072>音乐聊天室</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/bgt/' target=_blank><font color=#6F7072>曝光台</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/zhuanti/' target=_blank><font color=#6F7072>热点专题</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/2004news/zgrw/' target=_blank><font color=#6F7072>中广人物</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/2004news/column/hct/' target=_blank><font color=#6F7072>中央少年广播合唱团</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.crftv.com.cn/' target=_blank><font color=#6F7072>中国广播影视报</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td width='9'></td>                                                                                                                     ");
document.write ("		</tr>                                                                                                                                    ");
document.write ("		<tr><td colspan='29' background='http://www.cnr.cn/js_images/js_pic_007.jpg' height='1'></td></tr>                                                            ");
document.write ("		</table>                                                                                                                                 ");
document.write ("		<table cellpadding=0 cellspacing=0 border=0 width='900'>                                                                                 ");
document.write ("		<tr>                                                                                                                                     ");
document.write ("		<td width='9'></td>                                                                                                                     ");
document.write ("		<td style='padding-top:5px' valign='top' align='left'><font color=#6F7072>|</font></td>                                                         ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/tbtj/' target=_blank><font color=#6F7072>特别推荐</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/shiting/' target=_blank><font color=#6F7072>中广演播厅</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/jijin/' target=_blank><font color=#6F7072>广播风景线</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/newspaper/' target=_blank><font color=#6F7072>新闻和报纸摘要</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/china/wbll/' target=_blank><font color=#6F7072>晚报浏览</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.nihaotw.com/minge/index.asp' target=_blank><font color=#6F7072>中国民歌榜</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/china/jrlt/' target=_blank><font color=#6F7072>今日论坛</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.cnr.cn/zgnc/' target=_blank><font color=#6F7072>中国农村报道</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href='http://www.1259045.com/' target=_blank><font color=#6F7072>彩铃</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td align='center' width'51' style='font-size:12px;padding-top:6px' valign='top'><a href=http://211.89.225.41/was40/wcmsearch.htm target=_blank><font color=#6F7072>搜索</font></a></td>      ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#6F7072>|</font></td>                                                        ");
document.write ("		<td width='9'></td>                                                                                                                     ");
document.write ("		</tr>                                                                                                                                    ");
document.write ("		<tr><td colspan='29' background='http://www.cnr.cn/js_images/js_pic_007.jpg' height='1'></td></tr>                                                            ");
document.write ("		</table>                                                                                                                                 ");
document.write ("		<table cellpadding='0' cellspacing='0' border='0' width='900'>                                        ");
document.write ("		<tr>                                                                                                                                     ");
document.write ("		<td width='15'></td>                                                                                                                     ");
document.write ("		<td width='72' style='font-size:12px;padding-top:6px' valign='top' align='center'><font color=#3A81D9>广播频率：</font></td>                                                      ");
document.write ("		<td width='51' style='font-size:12px;padding-top:6px' valign='top' align='center'><a href='http://www.cnr.cn/china/' target=_blank><font color=#3A81D9>中国之声</font></a></td> ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#3A81D9>|</font></td>                                                    ");
document.write ("		<td width='51' style='font-size:12px;padding-top:6px' valign='top' align='center'><a href='http://finance.cnr.cn/' target=_blank><font color=#3A81D9>经济之声</font></a></td> ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#3A81D9>|</font></td>                                                       ");
document.write ("		<td width='51' style='font-size:12px;padding-top:6px' valign='top' align='center'><a href='http://musicradio.cnr.cn/' target=_blank><font color=#3A81D9>音乐之声</font></a></td> ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#3A81D9>|</font></td>                                                       ");
document.write ("		<td width='51' style='font-size:12px;padding-top:6px' valign='top' align='center'><a href='http://fm1018.cnr.cn/'  target=_blank><font color=#3A81D9>都市之声</font></a></td> ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#3A81D9>|</font></td>                                                       ");
document.write ("		<td width='51' style='font-size:12px;padding-top:6px' valign='top' align='center'><a href='http://www.nihaotw.com/'  target=_blank><font color=#3A81D9>中华之声</font></a></td> ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#3A81D9>|</font></td>                                                       ");
document.write ("		<td width='51' style='font-size:12px;padding-top:6px' valign='top' align='center'><a href='http://www.nihaotw.com/'  target=_blank><font color=#3A81D9>神州之声</font></a></td> ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#3A81D9>|</font></td>                                                       ");
document.write ("		<td width='51' style='font-size:12px;padding-top:6px' valign='top' align='center'><a href='http://hxradio.cnr.cn/'  target=_blank><font color=#3A81D9>华夏之声</font></a></td> ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#3A81D9>|</font></td>                                                       ");
document.write ("		<td width='51' style='font-size:12px;padding-top:6px' valign='top' align='center'><a href='http://www.cnr.cn/minzu/' target=_blank><font color=#3A81D9>民族之声</font></a></td> ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#3A81D9>|</font></td>                                                       ");
document.write ("		<td width='51' style='font-size:12px;padding-top:6px' valign='top' align='center'><a href='http://www.cnr.cn/wyzs/	' target=_blank><font color=#3A81D9>文艺之声</font></a></td> ");
document.write ("		<td width='16' height='20'  style= valign='top' align='center'><img src='http://www.cnr.cn/js_images/js_001.gif' alt='' width='16' height='17' border='0'></td>                                                      ");
document.write ("		<td width='51' style='font-size:12px;padding-top:6px' valign='top' align='center'><font color=#3A81D9>银河台：</font></td>                                                      ");
document.write ("		<td width='30' style='font-size:12px;padding-top:6px' valign='top' align='center'><a href=http://www.radio.cn/  target=_blank><font color=#3A81D9>娱乐</font></a></td> ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#3A81D9>|</font></td>                                                       ");
document.write ("		<td width='51' style='font-size:12px;padding-top:6px' valign='top' align='center'><a href='http://www.radio.cn/fans/'  target=_blank><font color=#3A81D9>粉丝基地</font></a></td> ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#3A81D9>|</font></td>                                                       ");
document.write ("		<td width='51' style='font-size:12px;padding-top:6px' valign='top' align='center'><a href='http://www.radio.cn/game/'  target=_blank><font color=#3A81D9>游戏动漫</font></a></td> ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#3A81D9>|</font></td>                                                       ");
document.write ("		<td width='51' style='font-size:12px;padding-top:6px' valign='top' align='center'><a href='http://www.radio.cn/tuiguang.html'  target=_blank><font color=#3A81D9>电台联盟</font></a></td> ");
document.write ("		<td style='padding-top:5px' valign='top'><font color=#3A81D9>|</font></td>                                                       ");
document.write ("		<td width='51' style='font-size:12px;padding-top:6px' valign='top' align='center'><a href='http://www.radio.cn/music/'  target=_blank><font color=#3A81D9>银河音乐</font></a></td> ");
document.write ("		<td width='10'></td>                                                                                                                      ");
document.write ("		</tr>                                                                                                                                    ");
document.write ("		</table>                                                                                                                                 ");
document.write ("	</td>                                                                                                                                      ");
document.write ("</tr>                                                                                                                                       ");
document.write ("</table>                                                                                                                                    ");